### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by biyiemmy** [scrimba/learn-react-router-6#5]
caught (in promise) TypeError: Cannot read properties of null (reading 'vans')
    at HostVanDetails.jsx:11:42

<img width="1440" alt="Screenshot 2023-05-04 at 09 50 18" src="https://user-images.githubusercontent.com/74870372/236156776-5dbab99e-5753-41ab-a9d6-ee31408922e2.png">

**Comment by biyiemmy** [comment]
Solved

**Comment by sturgeonphillip** [comment]
@biyiemmy what did you do to solve this issue?

**Comment by biyiemmy** [comment]
Hi @sturgeonphillip 
I used params in solving it
